name:                karp-miller
version:             0.1.0.0
github:              "dixonary/karp-miller"
license:             BSD3
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           ""

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: An implementation of the Karp-Miller Tree Construction algorithm.

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- hspec
- QuickCheck
- megaparsec
- filepath
- mtl
- diagrams
- diagrams-lib
- diagrams-svg
- diagrams-contrib
- diagrams-core
- force-layout
- SVGFonts
- vass
- pretty-simple 
- duvet

default-extensions:
- RecordWildCards
- FlexibleInstances

library:
  source-dirs: src

tests:
  karp-miller-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - karp-miller
